import React from "react";
import Link from "next/link";
import { ShieldAlert, ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Legal Disclaimer | Akwa Ibom @ 39 Celebration",
  description:
    "Independent civic tech disclaimer for the Akwa Ibom @ 39 Anniversary Trivia and DP Generator platform.",
};

export default function DisclaimerPage() {
  return (
    <main className="flex-1 w-full max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8 space-y-8">
      <Link
        href="/"
        className="inline-flex items-center gap-2 text-xs font-semibold text-orange-400 hover:text-orange-300 transition"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Home
      </Link>

      <div className="space-y-4">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-500/10 border border-orange-500/30 text-orange-400 text-xs font-semibold">
          <ShieldAlert className="w-4 h-4" />
          <span>Independent Platform Notice</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
          Legal Disclaimer
        </h1>
        <p className="text-sm text-slate-400">
          Last updated: September 2026
        </p>
      </div>

      <div className="glass-panel p-6 sm:p-8 rounded-2xl border border-slate-800 space-y-6 text-sm text-slate-300 leading-relaxed">
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">1. Independent Tech Contribution</h2>
          <p>
            This anniversary celebration platform is an independent civic and cultural technology contribution developed by <strong>Sabi AI Technologies Ltd</strong>. It was designed to foster state pride, digital literacy, and community celebration for citizens at home and across the global diaspora.
          </p>
          <div className="p-4 rounded-xl bg-orange-500/10 border border-orange-500/20 text-orange-200 text-xs font-medium">
            <strong>Official Stance:</strong> This platform is not affiliated with, endorsed by, sponsored by, or officially representing the Akwa Ibom State Government, its ministries, departments, or agencies (MDAs).
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">2. Educational & Entertainment Nature</h2>
          <p>
            The quiz questions, commemorative scorecards, and custom Display Pictures (DPs) generated by this service are intended solely for educational, cultural, and celebratory purposes. While every effort has been made to verify historical accuracy regarding dates, landmarks, and state cultural trivia, the information is provided &quot;as is&quot; without warranties of any kind.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">3. Public User Submissions</h2>
          <p>
            Birthday wishes and congratulatory messages displayed on the public ticker are submitted by users. While automated sanitization and moderation filters are in place, Sabi AI Technologies does not endorse or assume liability for opinions expressed by independent users in their submitted wishes.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">4. Contact & Inquiries</h2>
          <p>
            For tech partnerships, feedback, or inquiries regarding this platform, please reach out directly to Sabi AI Technologies at{" "}
            <a
              href="https://www.sabiaitech.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-orange-400 hover:underline"
            >
              sabiaitech.com
            </a>.
          </p>
        </section>
      </div>
    </main>
  );
}
