import React from "react";
import Link from "next/link";
import { ShieldCheck, ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Technology Partner Disclaimer | Akwa Ibom @ 39 Celebration",
  description:
    "Technology partner disclaimer for the Akwa Ibom @ 39 Anniversary digital engagement platform powered by Sabi AI Technologies.",
};

export default function DisclaimerPage() {
  return (
    <main className="flex-1 w-full max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8 space-y-8">
      <Link
        href="/"
        className="inline-flex items-center gap-2 text-xs font-semibold text-orange-400 hover:text-orange-300 transition"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Home
      </Link>

      <div className="space-y-4">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-semibold">
          <ShieldCheck className="w-4 h-4" />
          <span>Technology Partner Disclaimer</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
          Technology Partner Disclaimer
        </h1>
        <p className="text-sm text-slate-400">
          Last updated: September 2026
        </p>
      </div>

      <div className="glass-panel p-6 sm:p-8 rounded-2xl border border-slate-800 space-y-6 text-sm text-slate-300 leading-relaxed">
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">1. Technology Partner Initiative</h2>
          <p>
            This platform is a civic technology initiative developed by <strong>Sabi AI Technologies</strong> to power the digital engagement for the Akwa Ibom @ 39 Anniversary and the ARISE Agenda. The Akwa Ibom @ 39 Anniversary Hub is developed in support of the Akwa Ibom State Government&apos;s anniversary celebrations to foster statehood pride, cultural heritage awareness, and civic participation across the 31 Local Government Areas and the diaspora.
          </p>
          <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/25 text-emerald-200 text-xs font-medium">
            <strong>Official Alignment:</strong> Developed by Sabi AI Technologies in support of the Akwa Ibom State Government&apos;s 39th Anniversary Celebrations and the ARISE Agenda.
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">2. Educational & Celebratory Purpose</h2>
          <p>
            The quiz questions, commemorative scorecards, and custom Display Pictures (DPs) generated by this platform are designed for educational, cultural, and celebratory purposes. While every effort has been made to verify historical accuracy regarding dates, landmarks, and state cultural trivia, information is provided &quot;as is&quot; in the celebratory spirit of the statehood jubilee.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">3. User-Generated Content & Moderation</h2>
          <p>
            The birthday wishes, messages, scores, and photos uploaded or submitted by participants represent the views of the individual users and do not necessarily reflect the official positions of Sabi AI Technologies or the Akwa Ibom State Government.
          </p>
          <p>
            The messages, scores, and photos generated or submitted by users on this platform are the sole responsibility of the individuals. Sabi AI Technologies and the Akwa Ibom State Government reserve the right to remove any content deemed inappropriate, offensive, defamatory, or contrary to the spirit of the celebrations.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">4. Client-Side Photo Processing & Data Privacy</h2>
          <p>
            When utilizing the Akwa Ibom @ 39 DP Generator to create your commemorative avatar, your uploaded portrait is processed entirely client-side inside your web browser using HTML5 Canvas. Uploaded photos are not permanently stored or transmitted to external servers. Demographic selections (such as LGA or diaspora residency) are grouped into high-level, anonymous aggregates solely for campaign analytics.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">5. Contact & Inquiries</h2>
          <p>
            For tech partnerships, inquiries, or feedback regarding this platform, please reach out directly to Sabi AI Technologies at{" "}
            <a
              href="https://www.sabiaitech.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-orange-400 hover:underline font-semibold"
            >
              sabiaitech.com
            </a>.
          </p>
        </section>
      </div>
    </main>
  );
}
